[package]
name = "blocos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.1"
rand = "0.8.5"
image = "0.24"
rusttype = { version = "0.9.0", features = ["gpu_cache"] }
